url: 'https://en.onepiece-cardgame.com/cardlist/'
driver_path: 'D:\Projects\One Piece TCG\edgedriver\msedgedriver.exe'
editions: ['EB-01', 'OP-07', 'OP-06', 'OP-05', 'OP-04', 'OP-03', 'OP-02', 'OP-01',
           'ST-13', 'ST-12', 'ST-11', 'ST-10', 'ST-09', 'ST-08', 'ST-07', 'ST-06',
           'ST-05', 'ST-04', 'ST-03', 'ST-02', 'ST-01', 'Promo', 'Other']

opensearch:
  host: 'localhost'
  port: '9200'
  user: 'admin'
  pwd: 'Op3ns34rch_'
